group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'group'
urlpatterns = [
    path('MainGroup',views.mainGroup, name="MainGroup"),
    path('AddGroup',views.AddGroup, name="AddGroup"),
    path('MyGroup',views.myGroup, name="MyGroup"),
    path('ViewGroup/<str:pk>',views.viewGroup, name="ViewGroup"),
    path('JoinGroup/<str:pk>',views.joinGroup, name="JoinGroup"),
    path('DeleteGroup/<str:pk>',views.deleteGroup, name="DeleteGroup"),
    path('UpdateGroup/<str:pk>',views.updateGroup, name="UpdateGroup"),

    path('MainGroup/Filter_SoilTag',views.Group_SoilTag, name="Group_SoilTag"),
    path('MainGroup/Filter_PlantTag',views.Group_PlantTag, name="Group_PlantTag"),

 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

marketplace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
# from .import index
from .views import *
# from .api import UserList, UserDetail, UserAuthentication

app_name = 'marketplace'
urlpatterns = [
    path('MainMarketplace',views.mainMarketplace, name="MainMarketplace"),
    path('SellProduct.html/<str:fk1>/',views.sellProduct, name="SellProduct"),
    path('DeleteProduct/<str:fk1>/',views.deleteProduct, name="DeleteProduct"),
    path('UpdateProduct.html/<str:fk1>/',views.updateProduct, name="UpdateProduct"),
    path('MyMarketplace',views.myMarketplace, name="MyMarketplace"),
    path('buy_now/<str:fk1>/<str:fk2>/',views.buy_now, name='buy_now'),
    path('add_to_basket/<str:fk1>/<str:fk2>/',views.add_to_basket, name='add_to_basket'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

orders/urls.py
from django.urls import path
#from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    path('history.html', views.history, name='history'),
    path('invoice.html/<str:fk1>/', views.invoice, name='invoice'),
    path('order_again/<str:transaction_code>/', views.order_again, name='order_again'),
    path('complete_order/', views.complete_order, name='complete_order'),
    path('cancel_order/', views.cancel_order, name='cancel_order'),
    path('SellHistory.html/<str:fk1>/',views.SellHistory, name="SellHistory"),
    path('update_order_status/',views.update_order_status, name='update_order_status'),
]

plantfeed/urls.py
from member import views
from sharing import views
from group import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import AuthorizationView
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index ),
    path('', include('member.urls')),
    path('sharing/', include('sharing.urls')),
    path('group/', include('group.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('basket/', include('basket.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('topic/', include('topic.urls')),
    # path('sso/', include('sso.provider.urls')),
    path('authorization/', views.custom_oauth_authorization, name='custom_oauth_authorization'),
    path('plantlink/login/', views.login_view, name='plantlinklogin'),
    path('token-exchange/', views.token_exchange_view, name='token_exchange'),
    path('authorize/successful', views.authorize, name='authorize'),
    path('authorization/deny', views.deny, name='deny'),
    path('api/user-data/', views.user_data_api, name='user_data_api'),
]

marketplace/views.py
from django.shortcuts import render
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
# from LOGIN.models import Person as FarmingPerson
# from LOGIN.models import Feed, Booking, Workshop, Group, Member 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
# from .forms import CreateInDiscussion, PersonForm, UserUpdateForm
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import post_save
from django.dispatch import receiver
from cryptography.fernet import Fernet
from member.models import Person
# from sharing.models import Feed
from .models import prodProduct
from basket.models import Basket
import re
# from .models import Person

# Create your views here.


#marketplace
# def mainMarketplace(request):
#     try:
#         marketplace=MarketplaceFeed.objects.all()
#         return render(request,'MainMarketplace.html',{'marketplace':marketplace})
#     except MarketplaceFeed.DoesNotExist:
#         raise Http404('Data does not exist')
    
def mainMarketplace(request):
    try:
        marketplace=prodProduct.objects.all()
        # allBasket=Basket.objects.all()
        
        person = Person.objects.get(Email=request.session['Email'])
        
        allBasket = Basket.objects.filter(Person_fk_id=person.id,is_checkout=0)
        user=Person.objects.all()
        return render(request,'MainMarketplace.html',{'marketplace':marketplace, 'allBasket':allBasket, 'person':person, 'user':user})
    except prodProduct.DoesNotExist:
        raise Http404('Data does not exist')
    
def myMarketplace(request):
    try:
        person = Person.objects.get(Email=request.session['Email'])
        marketplace=prodProduct.objects.filter(Person_fk=person)
        allBasket = Basket.objects.filter(Person_fk_id=person.id,is_checkout=0)
        user=Person.objects.all()
        return render(request,'MyMarketplace.html',{'marketplace':marketplace, 'allBasket':allBasket, 'person':person, 'user':user})
    except prodProduct.DoesNotExist:
        raise Http404('Data does not exist')
    
# def sellProduct(request, fk1):
#     person = Person.objects.get(pk=fk1)
#     if request.method=='POST':
#         product = prodProduct()
#         product.productName=request.POST.get('productName')
#         product.productDesc=request.POST.get('productDesc')
#         product.productPrice=request.POST.get('productPrice')
#         product.productCategory=request.POST.get('productCategory')
#         product.productStock=request.POST.get('productStock')
        
#         if len(request.FILES) != 0:
#             product.productPhoto=request.FILES['productPhoto']
        
#         product.Person_fk=person
        
#         product.save()

#         messages.success(request,'Product Has Been Added Succesfully..!')

#         return redirect('marketplace:MainMarketplace')
#     else :
#         return render(request,'SellProduct.html')
    
def sellProduct(request, fk1):
    person = Person.objects.get(pk=fk1)
    if request.method == 'POST':
        product = prodProduct()
        # Product Name Validation
        product.productName = request.POST.get('productName')
        if len(product.productName) > 30:
            messages.error(request, 'Product name cannot be more than 30 characters.')
            return redirect(request.META.get('HTTP_REFERER'))

        # Product Description Validation
        product.productDesc = request.POST.get('productDesc')
        if len(product.productDesc) > 500:
            messages.error(request, 'Product description cannot be more than 500 characters.')
            return redirect(request.META.get('HTTP_REFERER'))
        
        # Product Category Validation
        product.productCategory = request.POST.get('productCategory')
        customCategory = request.POST.get('customCategory')
        if product.productCategory == "None Selected":
            messages.error(request, 'Product category has to be selected')
            return redirect(request.META.get('HTTP_REFERER'))
        
        if product.productCategory == "Others" and customCategory:
            # Use custom category if "Others" is selected and custom category is provided
            product.productCategory = customCategory
        else:
            # Use the selected predefined category
            product.productCategory = product.productCategory

        # Product Price Validation
        product.productPrice = request.POST.get('productPrice')
        price_parts = product.productPrice.split('.')
        # Regular expression to match digits and optional decimal point
        price_pattern = r'^\d+(\.\d{1,2})?$'

        # Check if the input matches the pattern
        if not re.match(price_pattern, product.productPrice):
            messages.error(request, 'Product price should only contain digits and allow up to two digits after the decimal point.')
            return redirect(request.META.get('HTTP_REFERER'))
        elif len(price_parts) == 1:
            # No decimal point in the input, check if it consists of digits
            if not product.productPrice.isdigit():
                messages.error(request, 'Product price should only contain digits.')
                return redirect(request.META.get('HTTP_REFERER'))
        elif len(price_parts) == 2:
            # Input contains a decimal point, check the digits before and after the decimal point
            if not (price_parts[0].isdigit() and len(price_parts[1]) <= 2 and price_parts[1].isdigit()):
                messages.error(request, 'Product price should only contain digits and allow two digits after the decimal point.')
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            # Input contains more than one decimal point, invalid format
            messages.error(request, 'Invalid product price format.')
            return redirect(request.META.get('HTTP_REFERER'))

        # Product Stock Validation
        product.productStock = request.POST.get('productStock')
        if not product.productStock.isdigit():
            messages.error(request, 'Product stock should only contain digits.')
            return redirect(request.META.get('HTTP_REFERER'))
        
        if len(request.FILES) != 0:
            product.productPhoto = request.FILES['productPhoto']
        
        fss = FileSystemStorage()
        
        product.Person_fk=person
        
        product.save()

        messages.success(request,'Product Has Been Added Succesfully..!')

        return redirect('marketplace:MainMarketplace')
    else :
        return render(request,'SellProduct.html')
    
# def deleteProduct(request,fk1):
#     product = prodProduct.objects.get(pk=fk1)
    
#     try:
#         product = prodProduct.objects.get(pk=fk1)
#         product.deleteProduct()
#         return redirect('marketplace:MainMarketplace')
        
#     except prodProduct.DoesNotExist:
#         messages.success(request, 'The product does not exist')
#         return redirect('marketplace:MainMarketplace')

def deleteProduct(request, fk1):
    try:
        product = prodProduct.objects.get(pk=fk1)
        product.delete()  # Call delete() on the product instance
        messages.success(request, 'The product has been deleted successfully.')
    except prodProduct.DoesNotExist:
        messages.error(request, 'The product does not exist.')
    return redirect('marketplace:MainMarketplace')
    
# def updateProduct(request,fk1):
#     product = prodProduct.objects.get(pk=fk1) 
#     if request.method == 'POST':
#         product.productName=request.POST.get('productName')
#         product.productDesc=request.POST.get('productDesc')
#         product.productCategory=request.POST.get('productCategory')
#         product.productPrice=request.POST.get('productPrice')
#         product.productStock=request.POST.get('productStock')
        
#         if len(request.FILES) != 0:
#             product.productPhoto=request.FILES['productPhoto']
            
#         # fss = FileSystemStorage()
        
#         product.save()
        
#         return redirect('marketplace:MainMarketplace')
#     else:
#         return render(request, 'UpdateProduct.html', {'product':product})

def updateProduct(request, fk1):
    product = prodProduct.objects.get(pk=fk1) 
    if request.method == 'POST':
        # Product Name Validation
        product_name = request.POST.get('productName')
        if len(product_name) > 20:
            messages.error(request, 'Product name cannot be more than 20 characters.')
            return redirect(request.META.get('HTTP_REFERER'))

        # Product Description Validation
        product_desc = request.POST.get('productDesc')
        if len(product_desc) > 500:
            messages.error(request, 'Product description cannot be more than 500 characters.')
            return redirect(request.META.get('HTTP_REFERER'))
        
        # Product Category Validation
        product_category = request.POST.get('productCategory')
        customCategory = request.POST.get('customCategory')
        
        if product_category == "None Selected":
            messages.error(request, 'Product category has to be selected')
            return redirect(request.META.get('HTTP_REFERER'))
        
        if product_category == "Others" and customCategory:
            # Use custom category if "Others" is selected and custom category is provided
            product_category = customCategory
        else:
            # Use the selected predefined category
            product_category = product_category

        # Product Price Validation
        product_price = request.POST.get('productPrice')
        price_parts = product_price.split('.')
        # Regular expression to match digits and optional decimal point

marketplace/templates/MainMarketplace.html
<!doctype html>
<html lang="en">
<head>
    <style>
        .content {
          max-width: 750px;
          margin: auto;
          overflow-x: hidden;
          width: 200px;
                }
        table{
          border:4px solid black;
          margin: 0 auto;
          padding: 40px;
          width: fit-content;
            }

        img {
          max-width: 100%;
          height: auto;
          border: 1px solid #ddd;
          border-radius: 4px;
          align-items: center;
          padding: 5px;

          }
        .profileIcon{
          border-radius: 50%;

        }
        .m
        {
          margin-left:550px;
        }
        
        a.link-primary {
          display: inline-block;
          padding: 6px 10px;
          border-radius: 3px;
          background-color: #4CAF50;
          color: white;
          text-decoration: none;
          transition: background-color 0.2s ease-out;
        }

        a.link-primary:hover {
          background-color: #3e8e41;
          text-decoration: none;
          color:white;
        }
      </style>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>

{% comment %} {% if messages %}
  {% for message in messages %}
    <div id="message" class="alert alert-success">
      {{ message }}
    </div>
  {% endfor %}
{% endif %} {% endcomment %}

{% if messages %}
  {% for message in messages %}
    {% if message.tags == "error" %}
      <div id="error-message" class="alert alert-danger">
        {{ message }}
      </div>
    {% else %}
      <div id="message" class="alert alert-success">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

<script>
  setTimeout(function() {
    document.getElementById("message").style.display = "none";
  }, 5000);
</script>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

{% include 'header-marketplace.html' %}
<br/>

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="container">
        <div class="row">
          <div class="col-8">
            <body>  
              {% csrf_token %}
                <div class="container my-3 bg-light">
                  <label for="exampleFormControlTextarea1" style="font-size: 2em;" >Browse Marketplace</label>
                    <div class="row" style="float: right; padding: 5px">
                      <table style="border:none;margin: 0 auto;padding: 40px;width: fit-content;border-collapse: collapse; border-spacing: 0;">
                        <tr>
                          <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 200px;">
                            <a href="{% url 'marketplace:SellProduct' person.id %}" class="link-primary">
                              <label class="fa-solid fa-cart-plus"></label> Sell Product
                            </a> 
                          </td>
                          <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 200px;">
                            &nbsp &nbsp
                            <a href="{% url 'orders:SellHistory' person.id %}" class="link-primary">
                              <label class="fa-solid fa-clock-rotate-left"></label> Orders
                            </a> 
                          </td>
                        </tr>
                      </table>
                    </div>
                </div>                            
            
{% endblock content %}

{% block body %}
      {% csrf_token %}
      <div class="container">
        <section style="background-color: #F0F2F5;">
            <div class="container py-5">
              <div class="main-timeline-2">
                {% csrf_token %}
                {% if marketplace %}
                {% for item in marketplace reversed %}
                {% if item.productStock > 0 %}
                <div class="timeline-2 left-2">
                  <div class="card" style="width: 650px;">
                    <table style="border: 0; margin-right:550px">
                        <th>
                            <div class="user-image">
                                <img class="rounded-circle" src="media/{{ item.Person_fk.Photo }}" alt="..." style="width: 45px; height: 45px; margin: 10px;">
                            </div>
                        </th>
                        <th>
                            <div class="username">
                                <span class="username">{{ item.Person_fk.Username }}</span>
                            </div>               
                        </th>
                    </table>
                    
                    <div class="card-body p-4">
                      <b>{{item.productName}}</b>
                      
                    </div>
                    
                    <img src="media/{{item.productPhoto}}" class="card-img-top"
                      alt="Responsive image" style="width: 550px;margin-left: 45px;">
                      <table style="border: none;  ">
                        <th style="padding-bottom: 0; align-items: center;">
                          <p class="text-muted mb-4" style="font-size: x-small; padding: 0;" value="{{ item.timePosted }}"><i class="far fa-clock" aria-hidden="true"></i>{{ item.timePosted }}</p>
                      </th>
                    
                      <div class="card-body p-4">
                        <b>RM {{item.productPrice}}</b>
                        <b style="float: right">{{item.productStock}} stock left</b><br><br>
                        <p class="mb-0" value="{{ item.productDesc }}" style="text-align: justify;">{{ item.productDesc }}</p>
                        <br>
                        {% if item.Person_fk.Email != request.session.Email %}
                        
                        <form id="buy-form" method="post" action="{% url 'marketplace:add_to_basket' item.productid person.id %}">
                          {% csrf_token %} 
                          <input type="hidden" name="productqty" value="1">
                          <button type="submit" style="float: right; margin-right: 5px">Add to basket</button>
                        </form>
                      
                        <form id="buy-form" method="post" action="{% url 'marketplace:buy_now' item.productid person.id %}">
                          {% csrf_token %} 
                          <input type="hidden" name="productqty" value="1">
                          <button type="submit" style="float: right; margin-right: 10px" id="buy-now-btn">Buy now</button>
                        </form>
                    
                      <br><br>
                      {% endif %}
                      {% if item.Person_fk.Email == request.session.Email %}
                        {% comment %} <a href="{% url 'marketplace:DeleteProduct' item.productid %}" type="button" id="delete-button" style="visibility: visible; float: right; margin-right: 10px" onClick="deleteProduct()" class="btn btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                          <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                        </svg></a> {% endcomment %}
                      <a href="#" type="button" id="delete-button" style="visibility: visible; float: right; margin-right: 10px" data-toggle="modal" data-target="#confirmDeleteModal" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                          <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                        </svg>
                      </a>                  
                      <a href="{% url 'marketplace:UpdateProduct' item.productid %}" type="button" id="update-button" style="visibility: visible; margin-right: 10px; float: right" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                          <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                        </svg>
                      </a>
                      <br><br>
                      {% endif %}
                      <!-- Modal -->
                      <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Delete</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure you want to delete this product?
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              <button type="button" class="btn btn-danger" onclick="deleteProduct()">Delete</button>
                            </div>
                          </div>
                        </div>
                      </div>

                      <!-- Hidden input field to store product ID -->
                      <input type="hidden" id="productIdInput" value={{ item.productid }}>
                    </div>
                  </div>

                </div>
                {% endif %}
                {% endfor %}
                {% else %}
                  <div class="container text-center">
                    <h3 style="color: #6c757d;">Markeplace is empty right now. Start selling!</h3>
                  </div>
                {% endif %}
                
    </div>
    <br/>

  </div>
</body>
  </div>
</div>
</div>
</div>
</div>
</div>

</b>



</html>
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

<script>
  function deleteProduct() {
    window.alert("Product successfully deleted!");
  }

  // Function to set the product ID in a hidden input field
  function setProductId(productId) {
    document.getElementById('productIdInput').value = productId;
  }

  // Function to delete the product
  function deleteProduct() {
    var productId = document.getElementById('productIdInput').value;
    console.log('Deleting product with ID:', productId);
    // Redirect to the delete URL
    var deleteUrl = "{% url 'marketplace:DeleteProduct' fk1=0 %}".replace('0', productId);
    window.location.href = deleteUrl;
  }
</script>
{% endblock body %}