group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'group'
urlpatterns = [
    path('MainGroup',views.mainGroup, name="MainGroup"),
    path('AddGroup',views.AddGroup, name="AddGroup"),
    path('MyGroup',views.myGroup, name="MyGroup"),
    path('ViewGroup/<str:pk>',views.viewGroup, name="ViewGroup"),
    path('JoinGroup/<str:pk>',views.joinGroup, name="JoinGroup"),
    path('DeleteGroup/<str:pk>',views.deleteGroup, name="DeleteGroup"),
    path('UpdateGroup/<str:pk>',views.updateGroup, name="UpdateGroup"),

    path('MainGroup/Filter_SoilTag',views.Group_SoilTag, name="Group_SoilTag"),
    path('MainGroup/Filter_PlantTag',views.Group_PlantTag, name="Group_PlantTag"),

 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

marketplace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
# from .import index
from .views import *
# from .api import UserList, UserDetail, UserAuthentication

app_name = 'marketplace'
urlpatterns = [
    path('MainMarketplace',views.mainMarketplace, name="MainMarketplace"),
    path('SellProduct.html/<str:fk1>/',views.sellProduct, name="SellProduct"),
    path('DeleteProduct/<str:fk1>/',views.deleteProduct, name="DeleteProduct"),
    path('UpdateProduct.html/<str:fk1>/',views.updateProduct, name="UpdateProduct"),
    path('MyMarketplace',views.myMarketplace, name="MyMarketplace"),
    path('buy_now/<str:fk1>/<str:fk2>/',views.buy_now, name='buy_now'),
    path('add_to_basket/<str:fk1>/<str:fk2>/',views.add_to_basket, name='add_to_basket'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

plantfeed/urls.py
from member import views
from sharing import views
from group import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import AuthorizationView
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index ),
    path('', include('member.urls')),
    path('sharing/', include('sharing.urls')),
    path('group/', include('group.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('basket/', include('basket.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('topic/', include('topic.urls')),
    # path('sso/', include('sso.provider.urls')),
    path('authorization/', views.custom_oauth_authorization, name='custom_oauth_authorization'),
    path('plantlink/login/', views.login_view, name='plantlinklogin'),
    path('token-exchange/', views.token_exchange_view, name='token_exchange'),
    path('authorize/successful', views.authorize, name='authorize'),
    path('authorization/deny', views.deny, name='deny'),
    path('api/user-data/', views.user_data_api, name='user_data_api'),
]

sharing/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'sharing'
urlpatterns = [
    #path('MainSharing',views.mainSharing, name="MainSharing"),
    path('SharingGroup/<str:pk>',views.sharingGroup, name="SharingGroup"),
    path('UpdateSharing/<str:pk>',views.updateSharing, name="UpdateSharing"),
    path('DeleteSharing/<str:pk>', views.deleteSharing, name="DeleteSharing"),
    path('Forum/<str:pk>', views.viewForum, name="Forum"),
    path('MainSharing',views.mainSharing, name="MainSharing"),
    path('AddNewSharing',views.AddSharing, name="AddSharing"),
    #path(',../MainPageSharing.html/<str:pk>', views.addLikes, name="AddLikes"),
    path('AddComment/<str:pk>', views.addComment, name="AddComment"),
    path('UpdateComment/<str:pk>',views.updateComment, name="UpdateComment"),
    path('DeleteComment/<str:pk>', views.deleteComment, name="DeleteComment"),
    path('AddLikes/<str:pk>', views.AddLikes, name="AddLikes"),
    

    path('Forum/<str:pk>/Filter_SoilTag',views.Sharing_GeneralSoilTag, name="Sharing_GeneralSoilTag"),
    path('Forum/<str:pk>/Filter_PlantTag',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    # path('Sharing_PlantTag',views.Sharing_GeneralPlantTag, name="Sharing_GeneralPlantTag"),
    # path('Sharing_PlantTag/<str:plantTag>',views.Sharing_PlantTag, name="Sharing_PlantTag"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

topic/urls.py
from django.urls import path

from . import views

app_name = 'topic'

urlpatterns = [
    path('selectTopic',views.selectTopic,name="selectTopic"),
    path('viewSelectedTopic',views.viewSelectedTopic,name="viewSelectedTopic"),
    path('updateSelectedTopic',views.updateSelectedTopic,name="updateSelectedTopic"),
    path('suggestNewTopic',views.suggestNewTopic,name="suggestNewTopic"),
    path('Managetopic', views.managetopic, name="Managetopic"),
    
]

group/models.py
from django.db import models

from django.db import models, migrations
# from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.syndication.views import Feed
from member.models import Person, SoilTag, PlantTag

# Create your models here.

class Group_tbl(models.Model):
    
    Name = models.CharField(max_length=150)
    About = models.CharField(max_length=1000)
    Media = models.ImageField(upload_to='uploads/',default="")
    Username = models.ForeignKey(Person, on_delete=models.CASCADE)
    Age = models.CharField(max_length=100,default="")
    State = models.CharField(max_length=100,default="")

    def save(self):
        # group = self
        super().save()
        #super().save(using='farming')
        # return group
        return self.id
    
    
        
    def deleteRecordIgrow(self):
        super().delete()
    
    class Meta:
        db_table = 'group_tbl'


class GroupMembership(models.Model):
    
    GroupName = models.ForeignKey(Group_tbl, on_delete=models.CASCADE)
    GroupMember = models.ForeignKey(Person, on_delete=models.CASCADE)
    # joined_on = models.DateTimeField(default=datetime.now, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True, blank=True)

    def save(self):
        super().save()

    
    class Meta:
        
        unique_together = [['GroupName', 'GroupMember']]


class GroupSoilTagging(models.Model):

    GroupSoilTag = models.ForeignKey(Group_tbl, related_name="soilTagging", on_delete=models.CASCADE)    
    soilTag = models.ForeignKey(SoilTag, on_delete=models.CASCADE)
   
    class Meta:  
        unique_together = [['GroupSoilTag', 'soilTag']]

    def save(self):
        super().save()
   
    def deleteRecordIgrow(self):
        super().delete()


class GroupPlantTagging(models.Model):

    GroupPlantTag = models.ForeignKey(Group_tbl, related_name="plantTagging", on_delete=models.CASCADE)    
    plantTag = models.ForeignKey(PlantTag, on_delete=models.CASCADE)
   
    class Meta:  
        unique_together = [['GroupPlantTag', 'plantTag']]

    def save(self):
        super().save()
   
    def deleteRecordIgrow(self):
        super().delete()

group/forms.py
from django import forms
from .models import Group_tbl


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group_tbl
        fields = ('Name', 'About', 'Media')

group/templates/AddNewGroup.html
<!doctype html>
<html lang="en">

<head>
  <style>
    .content {
      max-width: 500px;
      margin: auto;
    }

    table {
      border: 4px solid black;
      margin: 0 auto;
      padding: 40px;
      width: fit-content;
    }

    .panel {
    margin-bottom: 30px;
    color: #696969;
    background-color: #fff;
    border-radius: 5px;
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.08);
}
  </style>
</head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1> -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
  integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>



<{% include 'header-group.html' %}
<br />

<p class="h3 text-center align-content: center;">Create Group</p><br />
    <!-- cuba enctype="multipart/form-data" -->
    <form method="POST" class="container text-left" enctype="multipart/form-data">
      <form class="row g-3">
        {% csrf_token %}
        <div class="col-md-4">
          <label for="inputName" class="form-label">Name : </label>
          <input type="text" name="Name" class="vTextField" maxlength="150" required="" id="id_Name">
        </div>
        <br />
        <div class="col-12">
          <label for="inputAbout" class="form-label">About : </label>
          <input type="text" name="About" class="vTextField" maxlength="150" required="" id="id_About">
        </div>
        <br />
        <div class="col-12">
          <label for="inputImage" class="form-label">Media : </label>
          <input type="file" class="form-control" id="inputMedia" name="Photo" placeholder="Enter Media"
            accept=".doc, .docx, .pdf, .txt, image/*" required>
        </div>
        <br />

        <div class="col-md-6">
          <label for="inputAge" class="form-label">Age Class : </label>
          <select id="inputAge" name="Age" required>
            <option selected disabled=true>--select age class --</option>
            <option value="Teenagers">Teenagers</option>
            <option value="Young Adults">Young Adults</option>
            <option value="Adults">Adults</option>
            <option value="Senior">Senior</option>
            <option value="No Age Restriction">No Age Restriction</option>
          </select>
        </div>
        <br />

        <div class="col-md-6">
          <label for="inputLocation" class="form-label">Location : </label>
          <select id="inputLocation" name="State" required>
            <option selected disabled=true>--select state --</option>
            <option value="Johor">Johor</option>
            <option value="Kedah">Kedah</option>
            <option value="Kelantan">Kelantan</option>
            <option value="Melaka">Melaka</option>
            <option value="Negeri Sembilan">Negeri Sembilan</option>
            <option value="Pahang">Pahang</option>
            <option value="Pulau Pinang">Pulau Pinang</option>
            <option value="Perak">Perak</option>
            <option value="Perlis">Perlis</option>
            <option value="Sabah">Sabah</option>
            <option value="Sarawak">Sarawak</option>
            <option value="Selangor">Selangor</option>
            <option value="Terengganu">Terengganu</option>
            <option value="W.P. Kuala Lumpur">W.P. Kuala Lumpur</option>
          </select>
        </div>
        <br />

        <div class="col-md-6">
          <label for="inputSoil" class="form-label">Soil Tag : </label><br>
          {% for soilTag in SoilTag %}
          <input type="checkbox" name="SoilTag" value="{{soilTag.id}}" id="{{soilTag.id}}"><label
            for="{{soilTag.id}}">{{soilTag.SoilTagName}}</label><br>
          {% endfor %}
        </div>
        <br />
        <div class="col-md-6">
          <label for="inputPlant" class="form-label">Plant Tag : </label><br>
          {% for plantTag in PlantTag %}
          <input type="checkbox" name="PlantTag" value="{{plantTag.id}}" id="{{plantTag.id}}"><label
            for="{{plantTag.id}}">{{plantTag.PlantTagName}}</label><br>
          {% endfor %}
        </div>

        <br/>

        </div>

        <div class="col-12">
          <button type="submit" class="btn btn-success " value="Add">Create</button>
        </div>

      </form>
      <br /><br />
      {% if messages %}
      <hr>
      {% for msg in messages %}
      <b>{{msg}}</b>
      {% endfor %}
      <hr>
      {% endif %}
      <br /><br />

</body>

</html>

group/templates/MainPageGroup.html
<!doctype html>
<html lang="en">

<head>
  <style>
    .content {
      max-width: 500px;
      margin: auto;
    }

    table {
      border: 4px solid black;
      margin: 0 auto;
      padding: 40px;
      width: fit-content;
      
    }

    .panel {
    margin-bottom: 30px;
    color: #696969;
    background-color: #fff;
    border-radius: 5px;
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.08);
}
  </style>
</head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1> -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
  integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>



  {% include 'header-group.html' %}
  
<br />
{% block content %}

  <body>
    <div class="container">
    {% csrf_token %}
    <div class="container bg-light" style="text-align: center;">
      <label for="exampleFormControlTextarea1" style="font-size: 2em;">Group</label>     
    </div>
    <br/>
    <div class="col-12">
      <a class="btn btn-primary" href="{% url 'group:AddGroup' %}" role="button">Add New Group</a>
    </div>
    <br/>
    <div class="col-12">
        <a class="btn btn-primary" href="{% url 'group:MyGroup' %}" role="button">My Group</a>
      </div>
      <br/>
  

    {% endblock content %}
     {% block body %}

    

    {% if context_SoilTags %}
    <div class="container">
      <form method="POST" class="container row g-3" action="{% url 'group:Group_SoilTag' %}">
        {% csrf_token %}
        <div class="container">
          <label for="inputSoil" class="form-label">Soil Tag : </label><br>
          {% for soilTag in context_SoilTags.SoilTags %}
          <input type="radio" name="SoilTag" value="{{ soilTag.id }}">{{ soilTag.SoilTagName }} <br>
          {% endfor %}
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-success " value="Filter">Filter</button>
        </div>
      </form>
    </div>
    <br/>
    {% elif context_PlantTags %}

    <div class="container">
      <form method="POST" class="container row g-3" action="{% url 'group:Group_PlantTag' %}" attribute>
        {% csrf_token %}
        <div class="container">
          <label for="inputPlant" class="form-label">Plant Tag : </label><br>
          {% for plantTag in context_PlantTags.PlantTags %}
          <input type="radio" name="PlantTag" value="{{ plantTag.id }}">{{ plantTag.PlantTagName }} <br>
          {% endfor %}
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-success " value="Filter">Filter</button>
        </div>
      </form>
    </div>
    <br />
    {% else %}
    <div class="container">
      <h5>Filter Group By Tags: </h5>
      <a href="{% url 'group:Group_SoilTag' %}" class="link-primary" target="_blank">Enable Soil Tags</a> ||
      <a href="{% url 'group:Group_PlantTag' %}" class="link-primary" target="_blank">Enable Plant Tags</a>

      <form method="POST" class="center">
        {% csrf_token %}
  
        <br /><br />
        <center>
          <div class="container">
            <div class="row">
              <table class="table">
                <div class="col-md-6">
  
                  <select id="inputAge" name="Age" required>
                    <option selected disabled=true>--select age class --</option>
                    <option value="Teenagers">Teenagers</option>
                    <option value="Young Adults">Young Adults</option>
                    <option value="Adults">Adults</option>
                    <option value="Senior">Senior</option>
                    <option value="No Age Restriction">No Age Restriction</option>
                  </select>
                
                &nbsp;
                <select id="inputLocation" name="State" required>
                  <option selected disabled=true>--select state --</option>
                  <option>Johor</option>
                  <option>Kedah</option>
                  <option>Kelantan</option>
                  <option>Melaka</option>
                  <option>Negeri Sembilan</option>
                  <option>Pahang</option>
                  <option>Pulau Pinang</option>
                  <option>Perak</option>
                  <option>Perlis</option>
                  <option>Sabah</option>
                  <option>Sarawak</option>
                  <option>Selangor</option>
                  <option>Terengganu</option>
                  <option>W.P. Kuala Lumpur</option>
                </select>
                &nbsp;&nbsp;
                <button type="submit" class="btn btn-success " value="Filter">Filter</button>
                <br>
                <br>
            </div>
            </div>
          </div>
        </center>
  
      </form>

    </div>
    <br />
    {% endif %}


    <form action="{% url 'group:AddGroup' %}" method="POST" class="center">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="container">
        <div class="row">
          <table class="table caption-top">
            <thead>
              <tr>
                <!-- <th scope="col">Name</th>
                <th scope="col">About</th> -->
                <th scope="col">Group Profile</th>
                <th scope="col">Details</th>
                <!-- <th scope="col">Age Class</th>
                <th scope="col">Location</th> -->
                <th scope="col">Tagging Details</th>
                <th scope="col">Action</th>

              </tr>
            </thead>
            <tbody>
              {% for group in group %}
              <tr>
                <!-- <th scope="row" value="{{ group.Name }}">{{ group.Name }}</th>
                <th scope="row" value="{{ group.About }}">{{ group.About }}</th> -->
                <th><img src="media/{{group.Media}}" width="240" /></th>
                <!-- <th scope="row" value="{{ group.Username.Name }}">{{ group.Username.Name }}</a></th>
                <th scope="row" value="{{ group.Age }}">{{ group.Age }}</th>
                <th scope="row" value="{{ group.State }}">{{ group.State }}</th> -->
                <th>
                    <h3 style="text-align: center;">Details</h3>
                    Name      : {{ group.Name }} <br>
                    About     : {{ group.About }} <br>
                    Admin     : {{ group.Username.Name }} <br>
                    Age Class : {{ group.Age }} <br>
                    State     : {{ group.State }} <br>
                </th>

                <th>
                  {% if group.soilTagging.all %}
                  <!-- <i>Soil Tagging:</i> -->
                  <i>
                    {% for soilTags in group.soilTagging.all %}
                    {{soilTags.soilTag.SoilTagName}} {% if not forloop.last %},{% endif %}
                    {% endfor %}
                  </i>
                  {% endif %}

                  {% if group.plantTagging.all %}
                  <!-- <i>Plant Tagging:</i> -->
                  <i>
                    {% for plantTags in group.plantTagging.all %}
                    {{plantTags.plantTag.PlantTagName}} {% if not forloop.last %},{% endif %}
                    {% endfor %}
                  </i>
                  {% endif %}
                </th>
                {% if group.Username.Email != request.session.Email and groupMember.GroupMember.Email != request.session.Email %}
                <th>
                  <a href="{% url 'group:JoinGroup' group.id %}" class="btn btn-block">Join</a><br>
                  <a href="{% url 'group:ViewGroup' group.id %}" class="btn btn-primary">View</a><br>
                </th>
                {% else %}
                <th style="text-align:center;">
                    <br>
                    <a href="#" class="btn btn-block">Joined</a><br>
                    <br>
                    <a href="{% url 'group:ViewGroup' group.id %}" class="btn btn-primary">View</a><br>
                </th>
                {% endif %}
                <!-- <td>
                    <button type="submit" class="btn btn-success " value="Add">Add</button>
                  </td> -->
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </form>


    {% if messages %}
    <hr />
    {% for msg in messages %}
    <b>{{msg}}</b><br />
    {% endfor %}
    <hr />
    {% endif %}

    {% endblock body %}

  </body>


</div>


<br /><br />
</html>

group/templates/header-group.html
<!doctype html>
<html lang="en">
    <div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
          <div class="p-4" style="background-color: #8FBC8F;">
            <h4 class="text-white">What are you looking for?</h4>
            <span class="text-muted">Search here...</span>
            <form class="form-inline my-2">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-primary" type="submit">Search</button>
            </form>
          </div>
          
        </div>
        <nav class="navbar navbar-dark bg-success">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </nav>
      </div>
    
      <nav class="navbar navbar-expand navbar-dark bg-success">
        <a class="navbar-brand" href="#">P  L  A  N  T  F  E  E  D</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sharing:MainSharing' %}">Sharing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href=" {% url 'group:MainGroup' %}">Group</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'MemberMainPage' %}">Member</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Workshop</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Marketplace
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'marketplace:MainMarketplace' %}">Browse Marketplace<span class="sr-only">(current)</span></a>
                <a class="dropdown-item" href="{% url 'marketplace:MyMarketplace' %}">My Marketplace</a>
              </div>
            </li>
            {% comment %} <li class="nav-item">
              <a class="nav-link" href="{% url 'marketplace:MainMarketplace' %}">Marketplace</a>
            </li> {% endcomment %}
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'topic:Managetopic' %}">Manage Topic</a>
            </li> {% endcomment %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'ViewProfile' %}">View Profile<span class="sr-only">(current)</span></a>
                <a class="dropdown-item" href="{% url 'EditProfile' %}">Edit Profile</a>
              </div>
            </li>
    
          </ul>
          <a class="btn bg-light" href="{% url 'Logout' %}">
            <img class="bi bi-arrow-bar-right">LOGOUT</img>
          </a>
        </div>
      </nav>
</html>