group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'group'
urlpatterns = [
    path('MainGroup',views.mainGroup, name="MainGroup"),
    path('AddGroup',views.AddGroup, name="AddGroup"),
    path('MyGroup',views.myGroup, name="MyGroup"),
    path('ViewGroup/<str:pk>',views.viewGroup, name="ViewGroup"),
    path('JoinGroup/<str:pk>',views.joinGroup, name="JoinGroup"),
    path('DeleteGroup/<str:pk>',views.deleteGroup, name="DeleteGroup"),
    path('UpdateGroup/<str:pk>',views.updateGroup, name="UpdateGroup"),

    path('MainGroup/Filter_SoilTag',views.Group_SoilTag, name="Group_SoilTag"),
    path('MainGroup/Filter_PlantTag',views.Group_PlantTag, name="Group_PlantTag"),

 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

marketplace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
# from .import index
from .views import *
# from .api import UserList, UserDetail, UserAuthentication

app_name = 'marketplace'
urlpatterns = [
    path('MainMarketplace',views.mainMarketplace, name="MainMarketplace"),
    path('SellProduct.html/<str:fk1>/',views.sellProduct, name="SellProduct"),
    path('DeleteProduct/<str:fk1>/',views.deleteProduct, name="DeleteProduct"),
    path('UpdateProduct.html/<str:fk1>/',views.updateProduct, name="UpdateProduct"),
    path('MyMarketplace',views.myMarketplace, name="MyMarketplace"),
    path('buy_now/<str:fk1>/<str:fk2>/',views.buy_now, name='buy_now'),
    path('add_to_basket/<str:fk1>/<str:fk2>/',views.add_to_basket, name='add_to_basket'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

plantfeed/urls.py
from member import views
from sharing import views
from group import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import AuthorizationView
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index ),
    path('', include('member.urls')),
    path('sharing/', include('sharing.urls')),
    path('group/', include('group.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('basket/', include('basket.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('topic/', include('topic.urls')),
    # path('sso/', include('sso.provider.urls')),
    path('authorization/', views.custom_oauth_authorization, name='custom_oauth_authorization'),
    path('plantlink/login/', views.login_view, name='plantlinklogin'),
    path('token-exchange/', views.token_exchange_view, name='token_exchange'),
    path('authorize/successful', views.authorize, name='authorize'),
    path('authorization/deny', views.deny, name='deny'),
    path('api/user-data/', views.user_data_api, name='user_data_api'),
]

sharing/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'sharing'
urlpatterns = [
    #path('MainSharing',views.mainSharing, name="MainSharing"),
    path('SharingGroup/<str:pk>',views.sharingGroup, name="SharingGroup"),
    path('UpdateSharing/<str:pk>',views.updateSharing, name="UpdateSharing"),
    path('DeleteSharing/<str:pk>', views.deleteSharing, name="DeleteSharing"),
    path('Forum/<str:pk>', views.viewForum, name="Forum"),
    path('MainSharing',views.mainSharing, name="MainSharing"),
    path('AddNewSharing',views.AddSharing, name="AddSharing"),
    #path(',../MainPageSharing.html/<str:pk>', views.addLikes, name="AddLikes"),
    path('AddComment/<str:pk>', views.addComment, name="AddComment"),
    path('UpdateComment/<str:pk>',views.updateComment, name="UpdateComment"),
    path('DeleteComment/<str:pk>', views.deleteComment, name="DeleteComment"),
    path('AddLikes/<str:pk>', views.AddLikes, name="AddLikes"),
    

    path('Forum/<str:pk>/Filter_SoilTag',views.Sharing_GeneralSoilTag, name="Sharing_GeneralSoilTag"),
    path('Forum/<str:pk>/Filter_PlantTag',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    # path('Sharing_PlantTag',views.Sharing_GeneralPlantTag, name="Sharing_GeneralPlantTag"),
    # path('Sharing_PlantTag/<str:plantTag>',views.Sharing_PlantTag, name="Sharing_PlantTag"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

topic/urls.py
from django.urls import path

from . import views

app_name = 'topic'

urlpatterns = [
    path('selectTopic',views.selectTopic,name="selectTopic"),
    path('viewSelectedTopic',views.viewSelectedTopic,name="viewSelectedTopic"),
    path('updateSelectedTopic',views.updateSelectedTopic,name="updateSelectedTopic"),
    path('suggestNewTopic',views.suggestNewTopic,name="suggestNewTopic"),
    path('Managetopic', views.managetopic, name="Managetopic"),
    
]

sharing/views.py
from django.shortcuts import render
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
# from LOGIN.models import Person as FarmingPerson
# from LOGIN.models import Feed, Booking, Workshop, Group_tbl, Member 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
# from .forms import CreateInDiscussion, PersonForm, UserUpdateForm
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import post_save
from django.dispatch import receiver
from cryptography.fernet import Fernet
from .models import Feed, Comment, GroupTimeline, GroupTimelineComment,Likes
from group.models import Group_tbl, GroupMembership
from member.models import Person, SoilTag, PlantTag, Memberlist
from sharing.models import FeedSoilTagging, FeedPlantTagging

# Create your views here.


#sharing
def mainSharing(request):
    try:
        feed=Feed.objects.all()
        user=Person.objects.get(Email=request.session['Email'])
        user_group = GroupMembership.objects.filter(GroupMember_id=user)
        comment = Comment.objects.all()
        likes = Likes.objects.all()
        memberList = Memberlist.objects.all().filter(to_person=user)

        soilTags = SoilTag.objects.all()
        fss =FileSystemStorage()
        
        return render(request,'MainPageSharing.html',{'allfeed':feed ,'soilTags':soilTags, 'user_group':user_group, 'comment':comment, 'likes':likes, 'memberList':memberList})
    except Feed.DoesNotExist:
        raise Http404('Data does not exist')

def AddSharing(request):
    
    #group_forum = Group_tbl.objects.get(id=pk)
    creator=Person.objects.get(Email=request.session['Email'])
    soilTagList=SoilTag.objects.all()
    plantTagList=PlantTag.objects.all()

    if request.method=='POST':
        taggingSoil=SoilTag.objects.all()
        Title=request.POST.get('Title')
        Message=request.POST.get('Message')
        Skill=request.POST.get('Skill')
        State=request.POST.get('State')
        Photo=request.FILES['Photo']
        # Video=request.FILES['Video']
        #Photo=request.FILES.get('Photo',None)
        Video=request.FILES.get('Video', None)
        
        
        feed_id = Feed(Title=Title,Message=Message,Photo=Photo,Video=Video,Creator=creator,Skill=Skill,State=State).save()
        feed = Feed.objects.get(id=feed_id)
        allfeed = Feed.objects.all()

        soilTagsID = request.POST.getlist('SoilTag')
        plantTagsID = request.POST.getlist('PlantTag')

        for soilTagsID in soilTagsID:
            soilTag = SoilTag.objects.get(id=soilTagsID)
            FeedSoilTagging(FeedSoilTag = feed, soilTag=soilTag).save()

        for plantTagsID in plantTagsID:
            plantTag = PlantTag.objects.get(id=plantTagsID)
            FeedPlantTagging(FeedPlantTag = feed, plantTag=plantTag).save()

        messages.success(request,'The new feed is save succesfully..!')
        #return render(request,'MainPageSharing.html', {'feed':feed, 'allfeed':allfeed, 'creator':creator})
        return redirect('sharing:MainSharing')
    else :
        # taggingSoil=SoilTag.objects.all()
        return render(request,'AddNewSharing.html', {'SoilTag':soilTagList, 'PlantTag':plantTagList})

def sharingGroup(request, pk):
    
    group_forum = Group_tbl.objects.get(id=pk)
    creator=Person.objects.get(Email=request.session['Email'])
    soilTagList=SoilTag.objects.all()
    plantTagList=PlantTag.objects.all()

    if request.method=='POST':
        taggingSoil=SoilTag.objects.all()
        GroupTitle=request.POST.get('Title')
        GroupMessage=request.POST.get('Message')
        GroupSkill=request.POST.get('Skill')
        GroupState=request.POST.get('State')
        # Photo=request.FILES['Photo']
        # Video=request.FILES['Video']
        GroupPhoto=request.FILES.get('Photo',None)
        GroupVideo=request.FILES.get('Video', None)
        fss =FileSystemStorage()
        
        Gfeed_id = GroupTimeline(GroupTitle=GroupTitle,GroupMessage=GroupMessage,GroupPhoto=GroupPhoto,GroupVideo=GroupVideo,GroupFK=group_forum,CreatorFK=creator,GroupSkill=GroupSkill,GroupState=GroupState).save()
        Gfeed = GroupTimeline.objects.get(id=Gfeed_id)

        soilTagsID = request.POST.getlist('SoilTag')
        plantTagsID = request.POST.getlist('PlantTag')

        for soilTagsID in soilTagsID:
            soilTag = SoilTag.objects.get(id=soilTagsID)
            FeedSoilTagging(FeedSoilTag = Gfeed, soilTag=soilTag).save()

        for plantTagsID in plantTagsID:
            plantTag = PlantTag.objects.get(id=plantTagsID)
            FeedPlantTagging(FeedPlantTag = Gfeed, plantTag=plantTag).save()

        messages.success(request,'The new feed is save succesfully..!')
        return render(request,'sharing.html')

    else :
        # taggingSoil=SoilTag.objects.all()
        return render(request,'sharing.html', {'SoilTag':soilTagList, 'PlantTag':plantTagList})

  

def updateSharing(request, pk):
    # feed = Feed.objects.filter(id=pk)
    feed = Feed.objects.get(id=pk)
    soilTag=FeedSoilTagging.objects.filter(FeedSoilTag=feed)
    farming_soilTag=FeedSoilTagging.objects.filter(FeedSoilTag=feed)
    soilTagList=SoilTag.objects.all()
    plantTag=FeedPlantTagging.objects.filter(FeedPlantTag=feed)
    plantTagList=PlantTag.objects.all()
    
    if request.method=='POST':
        feed.Title=request.POST['Title']
        feed.Message=request.POST.get('Message')
        feed.State=request.POST.get('State')
        feed.Skill=request.POST.get('Skill')
        feed.Photo=request.FILES.get('Photo',None)
        feed.Video=request.FILES.get('Video', None)
        fss =FileSystemStorage()

        newSoilTags = request.POST.getlist('SoilTag')
        newPlantTags = request.POST.getlist('PlantTag')

        currentSoilTag=FeedSoilTagging.objects.filter(FeedSoilTag=feed)
        farmingSoilTag2=FeedSoilTagging.objects.filter(FeedSoilTag=feed)
        currentPlantTag=FeedPlantTagging.objects.filter(FeedPlantTag=feed)
        farmingPlantTag2=FeedPlantTagging.objects.filter(FeedPlantTag=feed)
        

        if soilTag:
            for currentSoilTag in currentSoilTag:
                currentSoilTag.deleteRecordFarming()
            for farmingSoilTag2 in farmingSoilTag2:
                farmingSoilTag2.deleteRecordIgrow()

        for newSoilTag in newSoilTags:
            new_soilTag = SoilTag.objects.get(id=newSoilTag)
            FeedSoilTagging(FeedSoilTag = feed, soilTag=new_soilTag).save()

        if plantTag:
            for currentPlantTag in currentPlantTag:
                currentPlantTag.deleteRecordFarming()
            for farmingPlantTag2 in farmingPlantTag2:
                farmingPlantTag2.deleteRecordIgrow()

        for newPlantTag in newPlantTags:
            new_plantTag = PlantTag.objects.get(id=newPlantTag)
            FeedPlantTagging(FeedPlantTag = feed, plantTag=new_plantTag).save()

        feed.save()

        messages.success(request,'The post of ' + request.POST['Title'] + " is updated succesfully..!")
        return redirect('../MainSharing')
    else:
        return render(request, 'UpdateSharing.html', {'feed': feed, 'SoilTag':soilTagList, 'currentSoilTag':soilTag, 'PlantTag':plantTagList, 'currentPlantTag':plantTag})


def deleteSharing(request,pk):
    try:
        feed=Feed.objects.get(id=pk)
        #feed2=Feed.objects.get(id=pk)

        data=Feed.objects.all()
        
        feed.deleteRecordIgrow()
            #feed2.deleteRecordFarming()
            # messages.success(request,'The ' + feed.Title + " is deleted succesfully..!")
        return redirect('../MainSharing')
        
        
    except Feed.DoesNotExist:
        messages.success(request,'No record of the feed!')
        return redirect('../MainSharing')

def AddLikes(request,pk):
    try:
        feed=Feed.objects.get(id=pk)
        liker=Person.objects.get(Email=request.session['Email'])
        
        #feed2=Feed.objects.get(id=pk)

        data=Feed.objects.all()
        
        Likes(Feed=feed,Liker=liker).save(),

            #feed2.deleteRecordFarming()
            # messages.success(request,'The ' + feed.Title + " is deleted succesfully..!")
        return redirect('../MainSharing')
        
        
    except Feed.DoesNotExist:
        messages.success(request,'No record of the feed!')
        return redirect('../MainSharing')


def viewForum(request, pk):
    if request.method=="POST":
        data = Group_tbl.objects.get(id=pk)
        Skill=request.POST.get('Skill')
        State=request.POST.get('State')
        # soilTags = FeedSoilTagging.objects.all()
        feed = Feed.objects.filter(Group = data)
        searchshare=Feed.objects.raw('select * from Feed where Skill="'+Skill+'" and State="'+State+'"')
        return render(request, 'Forum.html', {'feed': feed, 'data':data,'feed':searchshare})
    try:
            data = Group_tbl.objects.get(id=pk)
            feed = Feed.objects.filter(Group = data)
            return render(request,'Forum.html', {'feed':feed,'data':data})
    except Feed.DoesNotExist:
            raise Http404('Data does not exist') 

#def addLikes(request, pk):
#    liker=Person.objects.get(Email=request.session['Email'])
##    feed = Feed.objects.get(id=pk)
#    allfeed = Feed.objects.all()
#    likes = Likes.objects.all()
#    comment = Comment.objects.all()
    #group_id = feed.Group.id
    
#    if request.method=='POST':
        #like = request.POST.get('likes')
        #fss =FileSystemStorage()
        
#        Likes(Feed=feed,Liker=liker).save(),
       
#        return render(request, 'MainPageSharing.html',{'feed':feed, 'allfeed':allfeed, 'liker':liker, 'likes':likes, 'comment':comment})
#    else :
#        return render(request,'MainPageSharing.html', {'feed':feed, 'allfeed':allfeed})

sharing/templates/FilteredForum.html
<!DOCTYPE html>
<html>

<head>
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

  <style>
    .header {
      padding: 2px;
      font-size: 30px;
      text-align: center;
      background: white;
    }

    .leftcolumn {
      float: left;
      width: 100%;
    }

    .card {
      background-color: white;
      padding: 20px;
      margin-top: 20px;
    }

    .row:after {
      content: "";
      display: table;
      clear: both;
    }

    @media screen and (max-width: 800px) {

      .leftcolumn,
      .rightcolumn {
        width: 100%;
        padding: 0;
        padding-bottom: 20px;
      }
    }
  </style>
</head>


<body>
  <!-- <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1>

  <b>
    <div>
      <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="{% url 'Home' %}" role="tab"
            aria-controls="home" aria-selected="true">Home</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="sharing-tab" data-bs-toggle="tab" href="{% url 'sharing:MainSharing' %}"
            role="tab" aria-controls="sharing" aria-selected="true">Sharing</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="discussion-tab" data-bs-toggle="tab" href="{% url 'group:MainGroup' %}"
            role="tab" aria-controls="discussion" aria-selected="true">Group</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="friends-tab" data-bs-toggle="tab" href="{% url 'MainMember' %}" role="tab"
            aria-controls="friends" aria-selected="true">Member</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="workshop-tab" data-bs-toggle="tab" href="{% url 'workshop:Workshop' %}"
            role="tab" aria-controls="workshop" aria-selected="true">Workshop</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="{% url 'View' %}" role="tab"
            aria-controls="profile" aria-selected="true">Profile</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="{% url 'Logout' %}" role="tab"
            aria-controls="logout" aria-selected="true">Logout</a>
        </li>

      </ul>
    </div>
  </b> -->
  {% include 'header-sharing.html' %}
  
  <br />
  <br />
  <div class="header">
    {% csrf_token %}
    <div class="container my-3 bg-light">
      <label for="exampleFormControlTextarea1" style="font-size: 2em;">{{data.Name}}</label> <br />
      <!-- <label for="exampleFormControlTextarea1" style="font-size: 2em;" >Groud ID: {{data.id}}</label> -->
    </div>
  </div>
  <div class="container">
    <!-- <a href="{% url 'sharing:SharingGroup' data.id %}" class="link-primary" target="_blank">New Sharing</a> -->
    <a class="btn btn-primary" href="{% url 'sharing:SharingGroup' data.id %}" role="button" target="_blank">New Sharing</a>
  </div><br />


  <div class="container">
    <h9>Filter based on tags: {{chosen_soilTag.SoilTagName}}</h9>
  </div>

  {% for feed in filtered_feed reversed %}
  <div class="container">
    <div class="row">
      <div class="leftcolumn">
        <div class="card">
          {% csrf_token %}

          <h1>{{feed.FeedSoilTag.Title}}</h1>
          <h4><i>By {{feed.FeedSoilTag.Creator.Name}}</i></h4>
          <h9>Farming Skill: {{feed.Skill}}</h9>
          <h9>Location: {{feed.State}}</h9>
          <h9>{{feed.FeedSoilTag.created_at}}</h9>
          <br />
          <p><b>{{feed.FeedSoilTag.Message}}</b></p>
          <!-- <img
                src="{{ feed.FeedSoilTag.Photo }}"
                class="rounded-circle"
                width="30"
                height="30"
                alt=""
            /> -->
          {% if feed.FeedSoilTag.Photo %}
          <img style="border: 1px solid black;" src="{{MEDIA_URL}}/{{feed.FeedSoilTag.Photo}}" width="300" height="300"
            alt="pic" />
          <br>
          {% endif %}
          {% if feed.FeedSoilTag.Video %}
          <video width="500px" height="500px" controls style="border: 1px solid black;">
            <source src="{{MEDIA_URL}}/{{feed.FeedSoilTag.Video}}" type="video/mp4">
          </video>
          <br>
          {% endif %}

          {%for ori_feed in ori_feed reversed%}

          {% if feed.FeedSoilTag == ori_feed %}

          {% if ori_feed.soilTagging.all %}
          <i>Soil Tagging:</i>
          <i>
            {% for soilTags in ori_feed.soilTagging.all %}
            {{soilTags.soilTag.SoilTagName}} {% if not forloop.last %},{% endif %}
            {% endfor %}
          </i>
          {% endif %}

          {% if ori_feed.plantTagging.all %}
          <i>Plant Tagging:</i>
          <i>
            {% for plantTags in ori_feed.plantTagging.all %}
            {{plantTags.plantTag.PlantTagName}} {% if not forloop.last %},{% endif %}
            {% endfor %}
          </i>
          {% endif %}

          {% endif %}

          {% endfor %}
          <!-- endfor for ori_feed -->

          {% if feed.FeedSoilTag.Creator.Email == request.session.Email %}
          <div>
            <br />
            <a href="{% url 'sharing:UpdateSharing' feed.id %}" class="card-link">Edit</a>
            <a href="{% url 'sharing:DeleteSharing' feed.id %}" class="card-link">Delete</a>
          </div>

          {% endif %}
          <br />
          <hr>
          <h5>Comments...</h5>
          <br />
          {% if not feed.FeedSoilTag.comments.all %}
          No comments Yet...
          <br />
          <a href="{% url 'sharing:AddComment' feed.FeedSoilTag.id %}">Add Comment</a>

          {% else %}
          <a href="{% url 'sharing:AddComment' feed.FeedSoilTag.id %}">Add Comment</a>
          <br />
          {% for comment in feed.FeedSoilTag.comments.all %}
          <b>{{ comment.Commenter.Name }}</b>
          {{ comment.Message }}
          {% if request.session.Email == comment.Commenter.Email %}
          <a href="{% url 'sharing:UpdateComment' comment.id %}" class="card-link">Edit</a>
          <a href="{% url 'sharing:DeleteComment' comment.id %}" class="card-link">Delete</a>
          {% endif %}
          <br />
          <hr>
          <br />

          {% endfor %}


          {% endif %}

        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  {% if not filtered_feed %}
  <div class="container">
    <h7 style="text-align: center;"><i>No sharing related to this {{ chosen_soilTag.SoilTagName }} tag </i></h7>
  </div>
  {% endif %}
  <br />
  
</body>

</html>