group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'group'
urlpatterns = [
    path('MainGroup',views.mainGroup, name="MainGroup"),
    path('AddGroup',views.AddGroup, name="AddGroup"),
    path('MyGroup',views.myGroup, name="MyGroup"),
    path('ViewGroup/<str:pk>',views.viewGroup, name="ViewGroup"),
    path('JoinGroup/<str:pk>',views.joinGroup, name="JoinGroup"),
    path('DeleteGroup/<str:pk>',views.deleteGroup, name="DeleteGroup"),
    path('UpdateGroup/<str:pk>',views.updateGroup, name="UpdateGroup"),

    path('MainGroup/Filter_SoilTag',views.Group_SoilTag, name="Group_SoilTag"),
    path('MainGroup/Filter_PlantTag',views.Group_PlantTag, name="Group_PlantTag"),

 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

marketplace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
# from .import index
from .views import *
# from .api import UserList, UserDetail, UserAuthentication

app_name = 'marketplace'
urlpatterns = [
    path('MainMarketplace',views.mainMarketplace, name="MainMarketplace"),
    path('SellProduct.html/<str:fk1>/',views.sellProduct, name="SellProduct"),
    path('DeleteProduct/<str:fk1>/',views.deleteProduct, name="DeleteProduct"),
    path('UpdateProduct.html/<str:fk1>/',views.updateProduct, name="UpdateProduct"),
    path('MyMarketplace',views.myMarketplace, name="MyMarketplace"),
    path('buy_now/<str:fk1>/<str:fk2>/',views.buy_now, name='buy_now'),
    path('add_to_basket/<str:fk1>/<str:fk2>/',views.add_to_basket, name='add_to_basket'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

member/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.UserReg, name='Register'),
    path('Login', views.login, name='Login'),
    path('Home', views.homepage, name='Home'),
    path('HomeAdmin', views.homepageAdmin, name='HomeAdmin'),
    path('Logout', views.logout, name='Logout'),
    path('EditProfile', views.EditProfile, name='EditProfile'),
    path('ViewProfile', views.Profile, name='ViewProfile'),
    path('MemberMainPage', views.MainMember, name='MemberMainPage'),
    path('SearchMember', views.SearchMember, name='SearchMember'),
    path('SearchMember/<str:pk>', views.v2MainSearchbar, name='v2MainSearchbar'),
    path('sendMemberRequest/<str:userID>', views.sendMemberRequest, name='sendMemberRequest'),
    path('acceptMemberRequest/<str:requestID>', views.acceptMemberRequest, name='acceptMemberRequest'),
    path('ChatRoom/<str:room>', views.chatRoom, name='ChatRoom'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

plantfeed/urls.py
from member import views
from sharing import views
from group import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from oauth2_provider.views import AuthorizationView
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index ),
    path('', include('member.urls')),
    path('sharing/', include('sharing.urls')),
    path('group/', include('group.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('basket/', include('basket.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('topic/', include('topic.urls')),
    # path('sso/', include('sso.provider.urls')),
    path('authorization/', views.custom_oauth_authorization, name='custom_oauth_authorization'),
    path('plantlink/login/', views.login_view, name='plantlinklogin'),
    path('token-exchange/', views.token_exchange_view, name='token_exchange'),
    path('authorize/successful', views.authorize, name='authorize'),
    path('authorization/deny', views.deny, name='deny'),
    path('api/user-data/', views.user_data_api, name='user_data_api'),
]

sharing/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'sharing'
urlpatterns = [
    #path('MainSharing',views.mainSharing, name="MainSharing"),
    path('SharingGroup/<str:pk>',views.sharingGroup, name="SharingGroup"),
    path('UpdateSharing/<str:pk>',views.updateSharing, name="UpdateSharing"),
    path('DeleteSharing/<str:pk>', views.deleteSharing, name="DeleteSharing"),
    path('Forum/<str:pk>', views.viewForum, name="Forum"),
    path('MainSharing',views.mainSharing, name="MainSharing"),
    path('AddNewSharing',views.AddSharing, name="AddSharing"),
    #path(',../MainPageSharing.html/<str:pk>', views.addLikes, name="AddLikes"),
    path('AddComment/<str:pk>', views.addComment, name="AddComment"),
    path('UpdateComment/<str:pk>',views.updateComment, name="UpdateComment"),
    path('DeleteComment/<str:pk>', views.deleteComment, name="DeleteComment"),
    path('AddLikes/<str:pk>', views.AddLikes, name="AddLikes"),
    

    path('Forum/<str:pk>/Filter_SoilTag',views.Sharing_GeneralSoilTag, name="Sharing_GeneralSoilTag"),
    path('Forum/<str:pk>/Filter_PlantTag',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    # path('Sharing_PlantTag',views.Sharing_GeneralPlantTag, name="Sharing_GeneralPlantTag"),
    # path('Sharing_PlantTag/<str:plantTag>',views.Sharing_PlantTag, name="Sharing_PlantTag"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

topic/urls.py
from django.urls import path

from . import views

app_name = 'topic'

urlpatterns = [
    path('selectTopic',views.selectTopic,name="selectTopic"),
    path('viewSelectedTopic',views.viewSelectedTopic,name="viewSelectedTopic"),
    path('updateSelectedTopic',views.updateSelectedTopic,name="updateSelectedTopic"),
    path('suggestNewTopic',views.suggestNewTopic,name="suggestNewTopic"),
    path('Managetopic', views.managetopic, name="Managetopic"),
    
]

member/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django.utils import timezone

class PersonManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)
    
class Person(AbstractBaseUser, PermissionsMixin):
    Email = models.CharField(max_length=150, unique=True)
    Pass = models.CharField(max_length=150, default='')
    Username = models.CharField(max_length=150)
    Name = models.CharField(max_length=150)
    DateOfBirth = models.CharField(max_length=150)
    Age = models.IntegerField ()
    District = models.CharField(max_length=150)
    State = models.CharField(max_length=150)
    Occupation = models.CharField(max_length=150)
    About = models.CharField(max_length=150)
    Gender = models.CharField(max_length=1)
    MaritalStatus = models.CharField(max_length=150)
    UserLevel = models.CharField(max_length=10)
    
    objects = PersonManager()
    
    USERNAME_FIELD = 'Email'

    def upload_photo(self, filename):
        path = 'images/{}'.format(filename)
        return path

    Photo = models.ImageField(upload_to='images/', null=True, blank=True)

    class Meta:
        db_table = 'login_person'

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     self.pk = None
    
    def user_form(sender, instance, created, **kwargs):
        if created:
            Person.objects.create(user=instance)
            instance.Person.save()
            
# class Person(models.Model):
#     Email = models.CharField(max_length=150, unique=True)
#     Password = models.CharField(max_length=150)
#     Username = models.CharField(max_length=150)
#     Name = models.CharField(max_length=150)
#     DateOfBirth = models.CharField(max_length=150)
#     Age = models.IntegerField ()
#     District = models.CharField(max_length=150)
#     State = models.CharField(max_length=150)
#     Occupation = models.CharField(max_length=150)
#     About = models.CharField(max_length=150)
#     Gender = models.CharField(max_length=1)
#     MaritalStatus = models.CharField(max_length=150)
#     UserLevel = models.CharField(max_length=10)

#     def upload_photo(self, filename):
#         path = 'images/{}'.format(filename)
#         return path

#     Photo = models.ImageField(upload_to='images/', null=True, blank=True)

#     class Meta:
#         db_table = 'login_person'
        
#     def save(self):
#         super().save()
#         self.pk=None
    
#     def user_form(sender, instance, created, **kwargs):
#         if created:
#             Person.objects.create(user=instance)
#             instance.Person.save()

class MemberRequest(models.Model):

    class Meta:
        db_table = 'MemberRequest'
        # unique_together = [['to_user', 'from_user']]
    
    timestamp = models.DateTimeField(auto_now_add=True)
    to_user = models.ForeignKey(Person, related_name='to_user', on_delete=models.CASCADE)
    from_user = models.ForeignKey(Person, related_name='from_user', on_delete=models.CASCADE)
	

    def save(self):
        super().save()
        #super().save(using='farming')

    #def deleteRecordFarming(self):
    #    super().delete(using='farming')
        
    def deleteRecordIgrow(self):
        super().delete()

    class Meta:
        unique_together = [['to_user', 'from_user']]

class Room(models.Model):
    
    member1 = models.ForeignKey(Person, related_name='member1', on_delete=models.SET_NULL, null=True)
    member2 = models.ForeignKey(Person, related_name='member2', on_delete=models.SET_NULL, null=True)

    def save(self):
        super().save()
        #super().save(using='farming')
        return self.id
    

class Memberlist(models.Model):

    from_person = models.ForeignKey(Person, related_name='from_person', on_delete=models.CASCADE)
    to_person = models.ForeignKey(Person, related_name='to_person', on_delete=models.CASCADE)
    chatRoom = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)

    def save(self):
        super().save()
        #super().save(using='farming')

    #def deleteRecordFarming(self):
    #    super().delete(using='farming')
        
    def deleteRecordIgrow(self):
        super().delete()

    class Meta:
        
        unique_together = [['from_person', 'to_person']]



class Message(models.Model):
    value = models.TextField()
    date = models.DateTimeField(default=datetime.now, blank=True)
    sender = room = models.CharField(max_length=255)
    # sender = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)

    def save(self):
        super().save()
        #super().save(using='farming')
    


class SensorData(models.Model):
    class Meta:
        db_table = 'SensorData'    
    Detail = models.CharField(max_length=255)
    Name = models.CharField(max_length=150)

class Plants(models.Model):
    class Meta:
        db_table = 'Plants'
    Pictures = models.ImageField(upload_to='uploads/')
    Species = models.CharField(max_length=150)
    Types = models.CharField(max_length=150)


class Users(models.Model):
    username = models.CharField(max_length=10, unique=True) #AI190201
    password = models.CharField(max_length=30) #ninja saga
    name = models.CharField(max_length=100) #FAIZ BIN AB. HAMID
    age = models.IntegerField() #22
    ranking = models.FloatField() #2.5

    def upload_photo(self, filename):
        path = 'LOGIN/photo/{}'.format(filename)
        return path

    photo = models.ImageField(upload_to=upload_photo, null=True, blank=True)

    def upload_file(self, filename):
        path = 'LOGIN/file/{}'.format(filename)
        return path

    resume = models.ImageField(upload_to=upload_file, null=True, blank=True)

    def __str__(self):
        return f"{self.username} - {self.password}"


class SoilTag(models.Model):
    
    class Meta:
        db_table = 'SoilTag'  

    SoilTagName = models.CharField(max_length=50, unique=True)

    def save(self):
        super().save()
        super().save(using='farming')

    def deleteRecordFarming(self):
        super().delete(using='farming')
        
    def deleteRecordIgrow(self):
        super().delete()


class PlantTag(models.Model):
    
    class Meta:
        db_table = 'PlantTag'  

    PlantTagName = models.CharField(max_length=50, unique=True)

    def save(self):
        super().save()
        super().save(using='farming')

    def deleteRecordFarming(self):
        super().delete(using='farming')
        
    def deleteRecordIgrow(self):
        super().delete()



    

member/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from .models import *


class PersonForm(forms.ModelForm):
    class Meta:  
        model = Person 
        fields = "__all__"  

class UserUpdateForm(forms.ModelForm):
    Username = forms.CharField(required=True)
    Password = forms.CharField(required=True)
    Email = forms.EmailField(required=True)
    Name = forms.CharField(required=False)
    DateOfBirth = forms.CharField(required=False)
    Age = forms.CharField(required=False)
    District = forms.CharField(required=False)
    State = forms.CharField(required=False)
    Occupation = forms.CharField(required=False)
    About = forms.CharField(required=False)
    Gender = forms.CharField(required=False)
    MaritalStatus = forms.CharField(required=False)
    Photo = forms.ImageField(required=False)

    class Meta:
        model = Person
        fields = ['Email', 'Password', 'Username', 'Name', 'DateOfBirth', 'Age', 'District', 'State', 'Occupation', 'About', 'Gender', 'MaritalStatus', 'Photo']



class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = []

member/templates/editProfileForm2.html
<!doctype html>
<html lang="en">
<head>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');
      *{
        padding: 0;
        margin: 0;
        font-family: 'Poppins', sans-serif
    }
    
    .container{
        height: 1000px;;
        display:flex;
        justify-content:center;
        align-items:center;
        background-image: url("images/bg1.png");
        
    }

    .card{
        width:350px;
        height:960px;

        background-color:#fff;
        box-shadow:0px 15px 30px rgba(0,0,0,0.1);
        border-radius:10px;
        overflow:hidden
    }

    .card .info{
        padding:15px;
        display:flex;
        justify-content:space-between;
        border-bottom:1px solid #e1dede;
        background-color:#e5e5e5
    }
    
    .card .info button{
        height:30px;
        width:80px;
        border:none;
        color:#fff;
        border-radius:4px;
        background-color:#000;
        cursor:pointer;
        text-transform:uppercase
    }
    
    .card .forms{
        padding:15px
    }
    
    .card .inputs{
        display:flex;
        flex-direction:column;
        margin-bottom:10px
    }
    
    .card .inputs span{
        font-size:12px
    }
    
    .card .inputs input{
        height:40px;
        padding:0px 10px;
        font-size:17px;
        box-shadow:none;
        outline:none
    }
    
    .card .inputs input[type="text"][readonly]{
        border: 2px solid rgba(0,0,0,0)
    }
    </style>
</head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1> -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<script>
 </script>
 <!-- <b>
   <div>
     <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist" >
       <li class="nav-item" role="presentation">
         <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="{% url 'Home' %}" role="tab" aria-controls="home" aria-selected="true">Home</a>
       </li>
       <li class="nav-item" role="presentation">
         <a class="nav-link active" id="sharing-tab" data-bs-toggle="tab" href="#" role="tab" aria-controls="sharing" aria-selected="true">Sharing</a>
       </li>
       <li class="nav-item" role="presentation">
         <a class="nav-link active" id="discussion-tab" data-bs-toggle="tab" href="#" role="tab" aria-controls="discussion" aria-selected="true">Group</a>
       </li>
       <li class="nav-item" role="presentation">
        <a class="nav-link active" id="friends-tab" data-bs-toggle="tab" href="#" role="tab" aria-controls="friends" aria-selected="true">Member</a>
       </li>
       <li class="nav-item" role="presentation">
         <a class="nav-link active" id="workshop-tab" data-bs-toggle="tab" href="#" role="tab" aria-controls="workshop" aria-selected="true">Workshop</a>
        </li>
        <li class="nav-item" role="presentation">
            <div class="dropdown">
                <button class="dropbtn">Profile
                  <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                  <a href="{% url 'ViewProfile' %}">ViewProfile</a>
                  <a href="{% url 'EditProfile' %}">EditProfile</a>
                  
                </div>
              </div>
         <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="{% url 'EditProfile' %}" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
        </li>
       </li>
     </ul>
   </div>
 <br/> -->

 <div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="p-4" style="background-color: #8FBC8F;">
      <h4 class="text-white">What are you looking for?</h4>
      <span class="text-muted">Search here...</span>
      <form class="form-inline my-2">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
    
  </div>
  <nav class="navbar navbar-dark bg-success">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

<nav class="navbar navbar-expand navbar-dark bg-success">
  <a class="navbar-brand" href="#">P  L  A  N  T  F  E  E  D</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sharing:MainSharing' %}">Sharing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {% url 'group:MainGroup' %}">Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'MemberMainPage' %}">Member</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Workshop</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'marketplace:MainMarketplace' %}">Marketplace</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ViewProfile' %}">View Profile<span class="sr-only">(current)</span></a>
          <a class="dropdown-item active" href="{% url 'EditProfile' %}">Edit Profile</a>
        </div>
      </li>

    </ul>
    <a class="btn bg-light" href="{% url 'Logout' %}">
      <img class="bi bi-arrow-bar-right">LOGOUT</img>
    </a>
  </div>
</nav>

<div class="bg-success container" style="background-image: url('https://static.vecteezy.com/system/resources/previews/002/008/838/original/retro-styled-wavy-wallpaper-design-free-vector.jpg');">
    <form method="POST"><input type="hidden" name="csrfmiddlewaretoken" value="LUo8yACYeqTzOUYPx81ouuqmkcDTGHdxJkRjbmc5wCVtI7LYrhK5sUxWg2LWIEWX">
        {% csrf_token %}
        {%for person in person%}
        
        <div class="card"> 
            <div class="info"> 
        <span>Edit Your Profile</span> 
            </div> 
    <div class="forms"> 
        <div class="inputs"> 
            <span>Email</span> 
            <input type="text" readonly name="Email" value="{{ person.Email }}"   maxlength="150" required="" id="id_Email"> 
        </div>
        <div class="inputs"> 
            <span>Password</span> 
            <input type="text"  name="Password" value="{{ person.Password }}" class="vTextField" maxlength="150" required="" id="id_Password"> </div> 
        <div class="inputs"> 
            <span>Username</span> 
            <input type="text"  name="Username" value="{{ person.Username }}" class="vTextField" maxlength="150" required="" id="id_Username"> 
            </div>
        <div class="inputs"> 
            <span>Name</span> 
            <input type="text"  name="Name" value="{{ person.Name }}" class="vTextField" maxlength="150" required="" id="id_Name"> 
            </div> 
        <div class="inputs"> 
            <span>Date of Birth</span> 
            <input type="text"  name="DateOfBirth" value="{{ person.DateOfBirth }}" class="vTextField" maxlength="150" required="" id="id_DateOfBirth"> 
        </div>
        <div class="inputs"> 
            <span>Age</span> 
            <input type="number" name="Age" value="{{ person.Age }}" class="vIntegerField" required="" id="id_Age"> 
        </div> 
        <div class="inputs"> 
            <span>District</span> 
            <input type="text" name="District" value="{{ person.District }}" class="vTextField" maxlength="150" required="" id="id_District"> 
        </div> 
        <div class="inputs"> 
            <span>State</span> 
            <input type="text"  name="State" value="{{ person.State }}" class="vTextField" maxlength="150" required="" id="id_State"> 
        </div> 
        <div class="inputs"> 
            <span>Occupation</span> 
            <input type="text" name="Occupation" value="{{ person.Occupation }}" class="vTextField" maxlength="150" required="" id="id_Occupation"> 
        </div>
        <div class="inputs"> 
            <span>About</span> 
            <input type="text" name="About" value="{{ person.About }}" class="vTextField" maxlength="150" required="" id="id_About"> 
        </div>
        <div class="inputs"> 
            <span>Gender</span> 
            <input type="text"  name="Gender" value="{{ person.Gender }}" class="vTextField" maxlength="1" required="" id="id_Gender"> 
        </div>
        <div class="inputs"> 
            <span>Marital Status</span> 
            <input type="text"  name="MaritalStatus" value="{{ person.MaritalStatus }}" class="vTextField" maxlength="150" required="" id="id_MaritalStatus"> 
        </div>
    </div>
    {%endfor%}
        <div class="info"> <button type="submit" class="btn btn-success"  href="{% url 'EditProfile' %}">SAVE</button> 
    </div> </div>
    

</div>
</form>
</html>